version: '3'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  desafio-api:
    image: desafio
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_DRIVER_CLASS=org.postgresql.Driver
      - DATABASE_URL=jdbc:postgresql://postgres:5432/desafio
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DIALECT=org.hibernate.dialect.PostgreSQLDialect